default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  user: postgres
  password: password
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
 
development:
  <<: *default
  database: base_app_development

test:
  <<: *default
  database: base_app_test
  